# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  systemd.tmpfiles.rules = [
    "d /var/lib/wallos/db 0755 root root - -"
    "d /var/lib/wallos/logos 0755 root root - -"
  ];

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."wallos" = {
    image = "bellamy/wallos:latest";
    environment = {
      "TZ" = "Europe/Paris";
    };
    volumes = [
      "/var/lib/wallos/db:/var/www/html/db:rw"
      "/var/lib/wallos/logos:/var/www/html/images/uploads/logos:rw"
    ];
    ports = [
      "8282:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wallos"
      "--network=wallos_default"
    ];
  };
  systemd.services."podman-wallos" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wallos_default.service"
    ];
    requires = [
      "podman-network-wallos_default.service"
    ];
    partOf = [
      "podman-compose-wallos-root.target"
    ];
    wantedBy = [
      "podman-compose-wallos-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-wallos_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f wallos_default";
    };
    script = ''
      podman network inspect wallos_default || podman network create wallos_default
    '';
    partOf = [ "podman-compose-wallos-root.target" ];
    wantedBy = [ "podman-compose-wallos-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-wallos-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
